name: App

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths-ignore:
      - '.github/ISSUE_TEMPLATE'

jobs:
  build:
    runs-on: ubuntu-22.04
    if: ${{ !startsWith(github.event.head_commit.message, '[skip ci]') && github.repository_owner == 'EduardoA3677' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'temurin'
      - name: Submodule
        run: |
          git submodule update --init --recursive
      - name: Write key
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/master'
        run: |
          if [[ -n "${{ secrets.KEYSTORE }}" ]]; then
            touch signing.properties
            echo KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }} >> signing.properties
            echo KEYSTORE_ALIAS=${{ secrets.KEYSTORE_ALIAS }} >> signing.properties
            echo KEYSTORE_ALIAS_PASSWORD='${{ secrets.KEYSTORE_ALIAS_PASSWORD }}' >> signing.properties
            echo KEYSTORE_FILE=../key.jks >> signing.properties
            echo ${{ secrets.KEYSTORE }} | base64 --decode > key.jks
            echo "KEYSTORE_CREATED=true" >> $GITHUB_ENV
          fi
      - name: Write temporary key
        if: env.KEYSTORE_CREATED != 'true'
        run: |
          touch signing.properties
          keytool -genkey -alias a -dname CN=_ -storepass passwd -keypass passwd -keyalg RSA -keystore key.jks
          echo KEYSTORE_PASSWORD=passwd >> signing.properties
          echo KEYSTORE_ALIAS=a >> signing.properties
          echo KEYSTORE_ALIAS_PASSWORD=passwd >> signing.properties
          echo KEYSTORE_FILE=../key.jks >> signing.properties
      - name: Cache Gradle Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            !~/.gradle/caches/build-cache-*
          key: gradle-deps-app-${{ hashFiles('**/build.gradle') }}
          restore-keys: |
            gradle-deps
      - name: Cache Gradle Build
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches/build-cache-*
          key: gradle-builds-app-${{ github.sha }}
          restore-keys: |
            gradle-builds
      - name: Build with Gradle
        id: buildWithGradle
        run: |
          echo 'org.gradle.caching=true' >> gradle.properties
          echo 'org.gradle.parallel=true' >> gradle.properties
          echo 'org.gradle.vfs.watch=true' >> gradle.properties
          echo 'org.gradle.jvmargs=-Xmx2048m' >> gradle.properties
          ./gradlew :manager:assembleRelease :manager:assembleDebug -x lint
          echo "releaseName=`ls manager/build/outputs/apk/release/shizuku*-v*-release.apk | awk -F '(/|.apk)' '{print $6}'`" >> $GITHUB_OUTPUT
          echo "debugName=`ls manager/build/outputs/apk/debug/shizuku*-v*-debug.apk | awk -F '(/|.apk)' '{print $6}'`" >> $GITHUB_OUTPUT
      - name: Upload release
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.buildWithGradle.outputs.releaseName }}
          path: "manager/build/outputs/apk/release/*.apk"
      - name: Upload debug
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.buildWithGradle.outputs.debugName }}
          path: "manager/build/outputs/apk/debug/*.apk"
      - name: Upload mappings
        uses: actions/upload-artifact@v4
        with:
          name: mappings
          path: "manager/build/outputs/mapping/release"
